#+Title: Install tasks on dB

* PostgreSQL, Yoi dB creation
  
** Connect to Postgres

  1.- En una terminar o consola escribimos lo siguiente su y oprimimos enter  y a continuacion nos pediara la contraseña
      del root o super usuario.

      Ejemplo :
      #+begin_example
      user@foo:~$ su
      Contraseña:
      
      root@foo:/home/user#  <<--- el símbolo # nos indica que estamos como administradores o como super usuario.
      #+end_example

  2.- El siguiente paso es cambiarnos de usuario , el usuario administrador de Postgresql es postgres, entonces hacemos
      lo siguiente su - postgres y oprimimos enter, listo ya estamos como el usuario postgres.
      
      Ejemplo:
      #+begin_example
      root@foo:/home/user# su - postgres
      postgres@foo:~$
      #+end_example

  3.- Ahora nos conectamos a la terminal interactiva de postgres tecleando lo siguiente psql y oprimimos un enter.

      Ejemplo:
      #+begin_example
      postgres@foo:~$ psql
      
      psql (9.1.6)
      Digite «help» para obtener ayuda.

      postgres=#  <<-- Aquí nos indica que ya estamos en la terminal de postgres.
      #+end_example

** Create yoi_db and user.
  4.- Crear la base de datos, tecleamos el comando siguiente.
      #+begin_example
      CREATE DATABASE yoi_db;
      #+end_example

  5.-Crear el usuario de base de datos.
   #+begin_example
     CREATE USER yoi_dbuser with password 'd3f4ulty01p4ss$';
   #+end_example

  6.-Cambiar de propietario la base de datos impuestofacil
     #+begin_example
     ALTER DATABASE yoi_db OWNER TO yoi_dbuser;
     #+end_example


  7.- Para conectarnos a la base de datos impuestofacil tecleamos el siguiente comando
     
      \c yoi_db

      Ejemplo:
      #+begin_example
      postgres=# \c yoi_db
      Ahora está conectado a la base de datos «yoi_db» con el usuario «postgres».
      yoi_db=# <<-- Aqui nos indica que ya estamos adentro de la base de datos yoi_db.     
      #+end_example

** dB tables creation.
   
   Las relaciones de la base de datos se encuenta en el component /postmodern-tables-creation.lisp/, para crear las
   relaciones es necesario ejecutar las instrucciones del archivo.



* Create the admin user

 - Load the system with quicklisp
 
 - Change the data in db/admin-user-creation.lisp as you prefer.

 - In package :yoi execute the function insert-admin-user-on-db.

 - You can login using the user and password provided using the following url:

  http://localhost:9090/admin.ucw

 
