#+Title: Install tasks on dB

* PostgreSQL, Yoi dB creation
  
** Connect to Postgres

  1. From terminal/console, we need to be root (It depends on your PostgreSQL setup):

      #+begin_example
      user@foo:~$ su
      Contraseña:
      
      root@foo:/home/user#  <<---The # symbol tell us we are root now.
      #+end_example

  2. Next, we change the user to the postgres user:
      
      #+begin_example
      root@foo:/home/user# su - postgres
      postgres@foo:~$
      #+end_example

  3. Then we need to connect to the psql console;

      #+begin_example
      postgres@foo:~$ psql
      
      psql (9.1.6)
      Digite «help» para obtener ayuda.

      postgres=#  <<-- Here we can see we are now into psql console.
      #+end_example

** Create yoi_db and user.
  4. Create the data base
      #+begin_example
      CREATE DATABASE yoi_db;
      #+end_example

  5. Create the user with a password:
   #+begin_example
     CREATE USER yoi_dbuser with password 'd3f4ulty01p4ss$';
   #+end_example

  6. Change the dB owner:
     #+begin_example
     ALTER DATABASE yoi_db OWNER TO yoi_dbuser;
     #+end_example


  7. Coonnect to the dB:
     
      \c yoi_db


      #+begin_example
      postgres=# \c yoi_db
      Ahora está conectado a la base de datos «yoi_db» con el usuario «postgres».
      yoi_db=# <<-- As we can see now we are connected to the yoi_db dB.
      #+end_example

** dB tables creation.
   
   The definitions and code to create the dB tables are on the file /postmodern-tables-creation.lisp/, to create the tables in the dB we need to execute only one time the code in the file from the REPL, from inside the ws.ikki.yoi package. 

* Create the admin user

 - Load the system with quicklisp
 
 - Change the data in db/admin-user-creation.lisp as you prefer.

 - In package :yoi execute the function insert-admin-user-on-db.

 - You can login using the user and password provided using the following url:

  http://localhost:9090/admin.ucw

 
